# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ArcheDetection
                                 A QGIS plugin
 This plugin detects ground level objects from satellite imagery
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-08-22
        copyright            : (C) 2025 by Andrei Ancuta
        email                : andrei.ancuta@e-uvt.ro
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ArcheDetection class from file ArcheDetection.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .arche_detection import ArcheDetection
    return ArcheDetection(iface)
