# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ArcheDetection
                                 A QGIS plugin
 This plugin detects ground level objects from satellite imagery
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-08-22
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Andrei Ancuta
        email                : andrei.ancuta@e-uvt.ro
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import sys
class _NullWriter:
    def write(self, *args, **kwargs): pass
    def flush(self): pass
if getattr(sys, "stderr", None) is None:
    sys.stderr = _NullWriter()
if getattr(sys, "stdout", None) is None:
    sys.stdout = _NullWriter()
# -------------------------------------------------------

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core import QgsProject
from qgis.core import QgsProject, QgsApplication, Qgis
from PyQt5.QtWidgets import QProgressBar
from qgis.PyQt.QtWidgets import QApplication
from qgis.PyQt.QtGui import QCursor
from qgis.PyQt.QtCore import Qt
from PyQt5.QtWidgets import QFileDialog, QApplication
from PyQt5.QtGui import QCursor
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication, QFileDialog
from PyQt5.QtGui import QCursor
from PyQt5.QtCore import Qt
from qgis.PyQt.QtWidgets import QApplication, QProgressDialog
from qgis.PyQt.QtGui import QCursor
from qgis.PyQt.QtCore import Qt
import importlib

# ---------------------------------------------------------------------------
# Heavy worker imports (numpy, OpenCV, Ultralytics, TensorFlow, pandas,
# matplotlib, astrocult, ...) are deferred here behind a guard so the plugin
# can still LOAD in QGIS even when these external packages are not installed
# yet. If any are missing, _WORKER_IMPORT_ERROR is set and the plugin shows a
# friendly "please install dependencies" message instead of crashing on load.
# ---------------------------------------------------------------------------
_WORKER_IMPORT_ERROR = None
try:
    from .detection.yolo_runner import run_yolo_on_layer
    from .detection.crop_exporter import export_crops
    from .azimuth.azimuth_processor import run_azimuth_pipeline
    from .processing.binarizer import run_binarization_pipeline
    from .classification.resnet_runner import run_resnet_inference
    from .analysis.curvigram_runner import run_curvigram_from_resnet_csv_single, run_declination_curvigrams
    from .astronomy import declination_runner
    importlib.reload(declination_runner)
    run_declination_pipeline = declination_runner.run_declination_pipeline
except Exception as _e:  # ImportError, or anything a heavy module raises on import
    _WORKER_IMPORT_ERROR = _e


# Import name -> pip distribution name, for a friendly "what is missing" check.
_REQUIRED_IMPORTS = [
    ("numpy", "numpy"),
    ("cv2", "opencv-python-headless"),
    ("pandas", "pandas"),
    ("matplotlib", "matplotlib"),
    ("PIL", "Pillow"),
    ("scipy", "scipy"),
    ("requests", "requests"),
    ("torch", "torch"),
    ("torchvision", "torchvision"),
    ("tensorflow", "tensorflow"),
    ("ultralytics", "ultralytics"),
    ("astrocult", "astrocult"),
]


def _missing_dependencies():
    """Return the pip names of required packages that are not importable."""
    import importlib.util
    missing = []
    for module_name, dist_name in _REQUIRED_IMPORTS:
        try:
            if importlib.util.find_spec(module_name) is None:
                missing.append(dist_name)
        except Exception:
            missing.append(dist_name)
    return missing




import os
import sys
import multiprocessing as mp

def force_qgis_python_exe():
    """
    Ensure that any subprocess/multiprocessing spawned from within QGIS uses the
    bundled python.exe, not qgis-ltr-bin.exe (which would launch another QGIS instance).
    """
    try:
        # In QGIS, sys.exec_prefix usually points to .../apps/Python312
        py = os.path.join(sys.exec_prefix, "python.exe")
        if os.path.exists(py):
            # Make libraries that call subprocess via sys.executable use python.exe
            sys.executable = py

            # Make multiprocessing spawn use python.exe
            mp.set_executable(py)

            # Helps on Windows embedded/frozen-ish contexts
            mp.freeze_support()
    except Exception:
        pass

force_qgis_python_exe()



# Import the code for the dialog
from .ui.arche_detection_dialog import ArcheDetectionDialog
import os.path


class ArcheDetection:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'ArcheDetection_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&ArchaeoAstroInsight')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('ArcheDetection', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = os.path.join(self.plugin_dir, 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u''),
            callback=self.run,
            parent=self.iface.mainWindow()
            )
            
       
        

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&ArchaeoAstroInsight'),
                action)
            self.iface.removeToolBarIcon(action)


    def _ensure_dependencies(self):
        """Return True if the heavy runtime dependencies imported OK; otherwise
        show a friendly message (instead of crashing) and return False."""
        if _WORKER_IMPORT_ERROR is None:
            return True
        from qgis.PyQt.QtWidgets import QMessageBox
        missing = _missing_dependencies()
        detail = ("\n  - " + "\n  - ".join(missing)) if missing else ("\n\n" + str(_WORKER_IMPORT_ERROR))
        QMessageBox.warning(
            self.iface.mainWindow(),
            "ArchaeoAstroInsight - missing dependencies",
            "ArchaeoAstroInsight needs additional Python packages that are not "
            "installed in QGIS's Python yet:" + detail + "\n\n"
            "Please run the installer (02_install_global_admin.bat as "
            "Administrator), or follow the installation steps in the plugin "
            "README, then restart QGIS."
        )
        return False

    def run_export_crops(self):
        """Export PNG crops for detections (standalone action)."""
        if not self._ensure_dependencies():
            return
        from qgis.core import QgsVectorLayer
        from qgis.PyQt.QtWidgets import QInputDialog

        out_dir = QFileDialog.getExistingDirectory(
            self.iface.mainWindow(), self.tr("Choose output folder for PNG crops")
        )
        if not out_dir:
            return

        # Raster layer: prefer dialog selection if available
        raster_layer = None
        try:
            if getattr(self, "dlg", None) and self.dlg.isVisible():
                layer_id = self.dlg.rasterCombo.currentData()
                if layer_id:
                    raster_layer = QgsProject.instance().mapLayer(layer_id)
        except Exception:
            pass
        if raster_layer is None:
            raster_layer = self.iface.activeLayer()

        if raster_layer is None or raster_layer.type() != raster_layer.RasterLayer:
            self.iface.messageBar().pushWarning("ArchaeoAstroInsight ", "Please select a raster layer.")
            return

        # Pick detections layer
        candidates = [
            lyr for lyr in QgsProject.instance().mapLayers().values()
            if isinstance(lyr, QgsVectorLayer) and lyr.geometryType() == QgsVectorLayer.PointGeometry
        ]
        if not candidates:
            self.iface.messageBar().pushWarning("ArchaeoAstroInsight ", "No point vector layer found for detections.")
            return
        if len(candidates) == 1:
            detections_layer = candidates[0]
        else:
            items = [lyr.name() for lyr in candidates]
            i, ok = QInputDialog.getItem(self.iface.mainWindow(), "Pick detections layer", "Layer:", items, 0, False)
            if not ok:
                return
            detections_layer = candidates[items.index(i)]

        # Simple progress mapping
        def _export_cb(pct: int):
            QApplication.processEvents()

        try:
            QApplication.setOverrideCursor(QCursor(Qt.WaitCursor))
            self.iface.messageBar().pushInfo("ArchaeoAstroInsight ", "Exporting YOLO crops…")
            export_crops(
                raster_layer=raster_layer,
                vector_layer_name=detections_layer.name(),
                output_dir=out_dir,
                padding_px=6,
                make_square=False,
                resize_to=None,
                progress_cb=_export_cb,
                vector_layer_obj=detections_layer,
            )
            self.iface.messageBar().pushSuccess("ArchaeoAstroInsight ", f"Crops exported to: {out_dir}")
        except Exception as e:
            self.iface.messageBar().pushCritical("ArchaeoAstroInsight ", f"Export error: {e}")
        finally:
            QApplication.restoreOverrideCursor()
            
            
    def _merge_declination_outputs(self, outputs, output_dir):
        import pandas as pd
        import os

        dfs = []

        for label, path in outputs:
            if not path or not os.path.isfile(path):
                continue

            df = pd.read_csv(path)
            
            if "det_id" in df.columns:
                df = df.drop(columns=["det_id"])

            # Rename columns to method-specific
            rename_map = {}

            if "declination_deg" in df.columns:
                rename_map["declination_deg"] = f"declination_{label}"

            if "horizon_altitude_deg" in df.columns:
                rename_map["horizon_altitude_deg"] = f"horizon_altitude_{label}"
                
            if "azimuth_deg" in df.columns:
                rename_map["azimuth_deg"] = f"azimuth_{label}"

            df = df.rename(columns=rename_map)

            # Drop redundant column
            if "horizon_model" in df.columns:
                df = df.drop(columns=["horizon_model"])

            dfs.append(df)

        if not dfs:
            return

        base = dfs[0]

        for df in dfs[1:]:
            # Drop columns that already exist in base to avoid _x/_y duplication
            df = df.drop(columns=[c for c in ["observer_lat", "observer_lon"] if c in df.columns])

            base = base.merge(df, on="filename", how="outer")
            
            
            
        azimuth_cols = sorted([c for c in base.columns if c.startswith("azimuth_")])
        decl_cols = sorted([c for c in base.columns if c.startswith("declination_")])
        horizon_cols = sorted([c for c in base.columns if c.startswith("horizon_altitude_")])

        base = base[
            ["filename", "observer_lat", "observer_lon"]
            + azimuth_cols
            + horizon_cols
            + decl_cols
        ]

        final_path = os.path.join(output_dir, "declinations.csv")
        base.to_csv(final_path, index=False)

        print(f"[ArchaeoAstroInsight ] Combined declination saved to: {final_path}")


    def _build_results_csv(self, declination_outputs, out_dir, resnet_csv_path=None):
        """
        Build ONE centralized, clearly-named CSV at <out_dir>/Results/results.csv.

        Everything is joined on 'filename' (crops keep the same name through the whole
        pipeline, so the feature/"Helga" path and the ResNet path line up exactly).

        Column naming (client convention):
          - "feature algorithm"  -> "Helga Model"
          - "resnet"             -> "Resnet Model"

        Data sources:
          - declination_outputs : list of (label, path), label like 'feature_HWT',
            'resnet_SRTM'. Each per-method CSV supplies horizon + declination
            (and azimuth as a fallback) for that model x horizon-method.
          - features_results/azimuth_runs_*.csv (SUMMARY_mean) : authoritative Helga azimuth.
          - test_results/classes_*_prediction_*.csv (azimuth_deg) : authoritative ResNet azimuth.

        Only columns that actually have data (i.e. the horizon methods you checked) are
        written, so unchecked HWT/SRTM combinations simply don't appear.
        """
        import os
        import pandas as pd

        # Client-facing model names
        MODEL_NAME = {"feature": "Helga Model", "resnet": "Resnet Model"}

        # filename -> {column_name: value}
        table = {}
        lat = {}
        lon = {}

        def _cell(fn):
            return table.setdefault(fn, {})

        # 1) horizon + declination (+ azimuth fallback) from each per-method CSV
        for label, path in (declination_outputs or []):
            if not path or not os.path.isfile(path):
                continue
            az_src, _, method = str(label).partition("_")   # e.g. 'feature', 'HWT'
            model = MODEL_NAME.get(az_src, az_src)
            try:
                df = pd.read_csv(path)
            except Exception:
                continue
            cols = df.columns
            for _, r in df.iterrows():
                fn = str(r.get("filename", "")).strip()
                if not fn:
                    continue
                cell = _cell(fn)
                if "azimuth_deg" in cols:
                    cell[f"Azimuth {model} (deg)"] = r["azimuth_deg"]          # fallback
                if method and "horizon_altitude_deg" in cols:
                    cell[f"Horizon {model} {method} (deg)"] = r["horizon_altitude_deg"]
                if method and "declination_deg" in cols:
                    cell[f"Declination {model} {method} (deg)"] = r["declination_deg"]
                if "observer_lat" in cols:
                    lat[fn] = r["observer_lat"]
                if "observer_lon" in cols:
                    lon[fn] = r["observer_lon"]

        # 2) Authoritative ResNet azimuth from test_results/classes_*_prediction_*.csv
        if not resnet_csv_path:
            tr = os.path.join(out_dir, "test_results")
            if os.path.isdir(tr):
                cands = [f for f in os.listdir(tr)
                         if f.startswith("classes_") and f.endswith(".csv")]
                if cands:
                    resnet_csv_path = os.path.join(tr, sorted(cands)[-1])
        if resnet_csv_path and os.path.isfile(resnet_csv_path):
            try:
                rdf = pd.read_csv(resnet_csv_path)
                if "filename" in rdf.columns and "azimuth_deg" in rdf.columns:
                    for _, r in rdf.iterrows():
                        fn = str(r["filename"]).strip()
                        if fn:
                            _cell(fn)["Azimuth Resnet Model (deg)"] = r["azimuth_deg"]
            except Exception:
                pass

        if not table:
            return None

        # 4) Assemble with a fixed, logical column order; keep only populated columns
        canonical = [
            "Azimuth Helga Model (deg)",
            "Azimuth Resnet Model (deg)",
            "Horizon Helga Model HWT (deg)",
            "Horizon Helga Model SRTM (deg)",
            "Horizon Resnet Model HWT (deg)",
            "Horizon Resnet Model SRTM (deg)",
            "Declination Helga Model HWT (deg)",
            "Declination Helga Model SRTM (deg)",
            "Declination Resnet Model HWT (deg)",
            "Declination Resnet Model SRTM (deg)",
        ]
        present = set()
        for cell in table.values():
            present.update(cell.keys())
        ordered_cols = [c for c in canonical if c in present]

        records = []
        for fn in sorted(table.keys()):
            cell = table[fn]
            rec = {"filename": fn}
            for c in ordered_cols:
                rec[c] = cell.get(c)
            rec["observer_lat"] = lat.get(fn)
            rec["observer_lon"] = lon.get(fn)
            records.append(rec)

        out_cols = ["filename"] + ordered_cols + ["observer_lat", "observer_lon"]
        df_out = pd.DataFrame.from_records(records, columns=out_cols)

        results_dir = os.path.join(out_dir, "Results")
        os.makedirs(results_dir, exist_ok=True)
        out_path = os.path.join(results_dir, "results.csv")
        df_out.to_csv(out_path, index=False)

        try:
            self.iface.messageBar().pushInfo(
                "ArchaeoAstroInsight ", f"Centralized results saved: {out_path}"
            )
        except Exception:
            pass
        print(f"[ArchaeoAstroInsight ] Centralized results saved to: {out_path}")
        return out_path




    def run(self):
        if not self._ensure_dependencies():
            return
        # Create dialog once
        if self.first_start is True:
            self.first_start = False
            self.dlg = ArcheDetectionDialog()

        # Refresh raster list
        if hasattr(self.dlg, "populate_raster_combo"):
            self.dlg.populate_raster_combo()

        # Show dialog
        self.dlg.show()
        if not self.dlg.exec_():
            return

        # Inputs
        layer_id = self.dlg.rasterCombo.currentData()
        layer = QgsProject.instance().mapLayer(layer_id) if layer_id else None
        if layer is None:
            self.iface.messageBar().pushWarning("ArchaeoAstroInsight ", "Please select a raster layer.")
            return

        # NEW: detect polygon mode from the dialog
        polygon_mode = hasattr(self.dlg, "is_polygon_mode") and self.dlg.is_polygon_mode()

        conf = float(self.dlg.confidenceSpinBox.value())
        
        # Tile overlap percent (0..99), default 25 if missing
        try:
            if hasattr(self.dlg, "tile_overlap_percent"):
                overlap_percent = int(self.dlg.tile_overlap_percent())
            elif hasattr(self.dlg, "overlapSpinBox"):
                overlap_percent = int(self.dlg.overlapSpinBox.value())
            else:
                overlap_percent = 25
        except Exception:
            overlap_percent = 25

        overlap_percent = max(0, min(overlap_percent, 99))


        import os
        from qgis.PyQt.QtCore import QSettings

        # Only validate YOLO model if we're NOT in polygon mode
        model_path = self.dlg.modelPathEdit.text().strip() if hasattr(self.dlg, "modelPathEdit") else ""
        if not polygon_mode:
            if not model_path or not os.path.isfile(model_path):
                self.iface.messageBar().pushCritical("ArchaeoAstroInsight ", "Please choose a valid YOLO model (.pt/.pth).")
                return
            # remember last used model
            QSettings().setValue("ArcheDetection/model_path", model_path)
        

        # Progress dialog (modal) — stays up until EVERYTHING is finished
        prog = QProgressDialog("Running YOLO detection…", "Cancel", 0, 100, self.iface.mainWindow())
        prog.setWindowTitle("ArchaeoAstroInsight  – Progress")
        prog.setWindowModality(Qt.WindowModal)
        prog.setMinimumDuration(0)
        prog.setAutoClose(False)   # keep control; we’ll close explicitly at the very end
        prog.setAutoReset(True)
        prog.setValue(0)

        canceled = {"flag": False}
        
        def _progress_cb(pct: int):
            if canceled["flag"]:
                return
            prog.setValue(int(pct))
            QApplication.processEvents()
            if prog.wasCanceled():
                canceled["flag"] = True
       


        def _set_progress(pct: int):
            if canceled["flag"]:
                return
            prog.setValue(int(pct))
            QApplication.processEvents()
            if prog.wasCanceled():
                canceled["flag"] = True

        # Map a 0..100 callback into 0..80 range for detection
        def _yolo_cb(pct: int):
            _set_progress(min(80, int(pct * 0.8)))

        detections_layer = None
        try:
            QApplication.setOverrideCursor(QCursor(Qt.WaitCursor))

            if not polygon_mode:
                # ---- YOLO path ----
                self.iface.messageBar().pushInfo("ArchaeoAstroInsight ", "Running YOLO detection…")

                detections_layer = run_yolo_on_layer(
                    layer,
                    conf_threshold=conf,
                    model_path=model_path,
                    tile_overlap_percent=overlap_percent,   # <-- NEW
                    progress_cb=_progress_cb,
                    is_canceled=lambda: canceled["flag"]
                )


                if detections_layer is None or canceled["flag"]:
                    return

            else:
                # ---- Polygon (SHP) path: skip YOLO, pick the user's polygons layer ----
                poly_id = self.dlg.selected_polygon_layer_id() if hasattr(self.dlg, "selected_polygon_layer_id") else None
                detections_layer = QgsProject.instance().mapLayer(poly_id) if poly_id else None
                if detections_layer is None:
                    self.iface.messageBar().pushWarning("ArchaeoAstroInsight ", "Please select a polygons layer.")
                    return

                self.iface.messageBar().pushInfo("ArchaeoAstroInsight ", f"Using polygons layer: {detections_layer.name()}")
                prog.setLabelText("Processing existing polygons…")
                _set_progress(80)  # we’ll reuse the same 80–100% export window below


            # ---- Optional export (80..100%) ----
            if getattr(self.dlg, "exportCropsCheck", None) and self.dlg.exportCropsCheck.isChecked():
                out_dir = self.dlg.exportDirEdit.text().strip() if getattr(self.dlg, "exportDirEdit", None) else ""
                if not out_dir:
                    out_dir = QFileDialog.getExistingDirectory(self.iface.mainWindow(), "Choose output folder for PNG crops")
                    if not out_dir:
                        self.iface.messageBar().pushWarning("ArchaeoAstroInsight ", "Crop export skipped (no folder selected).")
                        return

                self.iface.messageBar().pushInfo("ArchaeoAstroInsight ", f"Exporting YOLO crops to: {out_dir}")
                prog.setLabelText("Exporting crops…")

                # Wrap export progress into 80..100
                def _export_cb(pct: int):
                    pct = max(0, min(100, int(pct)))
                    _set_progress(80 + int(pct * 0.20))  # 80 → 100

                export_crops(
                    raster_layer=layer,
                    vector_layer_name=detections_layer.name(),
                    output_dir=out_dir,
                    padding_px=6,
                    make_square=False,
                    resize_to=None,
                    progress_cb=_export_cb,
                    vector_layer_obj=detections_layer  # use the exact layer we just created
                )
            else:
                # no export requested — jump to 100
                _set_progress(100)
                
            # ... inside the try: block, right after export_crops(...) call succeeded
            if getattr(self.dlg, "resnetCheck", None) and self.dlg.resnetCheck.isChecked():
                prog.setLabelText("Preprocessing crops for ResNet…")
                # map azimuth progress 0..100 → 90..100
                def _az_cb(pct: int):
                    pct = max(0, min(100, int(pct)))
                    _set_progress(90 + int(pct * 0.10))
                run_azimuth_pipeline(out_dir, progress_cb=_az_cb)
                # Immediately run binarization on stage3_1 (no extra checks)
                stage3_folder = os.path.join(out_dir, "stage3_1")
                prog.setLabelText("Binarizing stage3_1…")

                def _bin_cb(pct: int):
                    # map 0..100 → 95..100 to keep a visible tail end of progress
                    pct = max(0, min(100, int(pct)))
                    _set_progress(95 + int(pct * 0.05))

                run_binarization_pipeline(stage3_folder, progress_cb=_bin_cb)
                
                
                # (Helga feature-detection removed in the ResNet-only light version)
                
                
                
                
                
                
                
                           # --- OPTIONAL: ResNet classification on exported crops ---
                # Runs only if "Also export crops" was checked AND "Classify with ResNet" is checked
                if getattr(self.dlg, "exportCropsCheck", None) and self.dlg.exportCropsCheck.isChecked():
                    if getattr(self.dlg, "resnetCheck", None) and self.dlg.resnetCheck.isChecked():

                        # Determine input crops folder for ResNet:
                        # - Prefer stage31_binary2 if azimuth+binarization ran
                        # - Else use the plain export folder (out_dir)
                        resnet_folders = []
                        if 'out_dir' in locals() and out_dir:
                            stage31_bin2 = os.path.join(out_dir, "stage31_binary2")
                            if os.path.isdir(stage31_bin2):
                                resnet_folders = [stage31_bin2]
                            elif os.path.isdir(out_dir):
                                resnet_folders = [out_dir]

                        # If nothing found, ask user to pick a folder
                        if not resnet_folders:
                            picked = QFileDialog.getExistingDirectory(self.iface.mainWindow(), "Pick folder with PNG crops")
                            if picked:
                                resnet_folders = [picked]

                        if not resnet_folders:
                            self.iface.messageBar().pushWarning("ArchaeoAstroInsight ", "ResNet skipped (no crops folder found).")
                        else:
                            # Get .keras path from dialog
                            resnet_model = self.dlg.resnetModelEdit.text().strip() if hasattr(self.dlg, "resnetModelEdit") else ""
                            if not resnet_model or not os.path.isfile(resnet_model):
                                self.iface.messageBar().pushCritical("ArchaeoAstroInsight ", "Please choose a valid ResNet .keras model.")
                            else:
                                prog.setLabelText("Classifying crops (ResNet)…")

                                # Map 0..100 to a visible tail (98..100) of your progress bar
                                def _resnet_cb(pct: int):
                                    pct = max(0, min(100, int(pct)))
                                    _set_progress(98 + int(pct * 0.02))

                                try:
                                    # Save results alongside other outputs
                                    results_base = out_dir if ('out_dir' in locals() and out_dir) else resnet_folders[0]
                                    resnet_csv_path = run_resnet_inference(
                                        folders=resnet_folders,
                                        keras_model_path=resnet_model,
                                        image_size=100,      # your training size
                                        num_classes=72,      # optional, used in CSV name
                                        batch_size=128,
                                        output_dir=os.path.join(results_base, "test_results"),
                                        progress_cb=_resnet_cb
                                    )
                                    self.iface.messageBar().pushInfo("ArchaeoAstroInsight ", f"ResNet CSV: {resnet_csv_path}")
                                except Exception as e:
                                    self.iface.messageBar().pushCritical("ArchaeoAstroInsight ", f"ResNet error: {e}")
                                    
                                    
                                    
                # --- astronomical declination calculation ---
                use_hwt     = self.dlg.use_declination_hwt()
                use_srtm    = self.dlg.use_declination_srtm()
                use_resnet  = self.dlg.use_resnet_azimuth()

                if use_hwt or use_srtm:

                    prog.setLabelText("Computing astronomical declinations…")

                    features_results_dir = os.path.join(out_dir, "features_results")

                    declination_outputs = []

                    # --- Azimuth sources to compute declinations for ---
                    azimuth_sources = []
                    if use_resnet:
                        azimuth_sources.append("resnet")

                    # --- Horizon methods (HWT = HeyWhatsThat online; SRTM = local DEM) ---
                    methods = []
                    if use_hwt:
                        methods.append(("HWT", False))
                    if use_srtm:
                        methods.append(("SRTM", True))

                    # --- Run each combination INDEPENDENTLY so a failure in one
                    #     (e.g. the HeyWhatsThat/HWT web service being unreachable)
                    #     does NOT abort the others (e.g. SRTM, computed locally). ---
                    for az_src in azimuth_sources:
                        for label, use_srtm_flag in methods:
                            try:
                                out = run_declination_pipeline(
                                    features_results_dir,
                                    detections_layer,
                                    use_srtm=use_srtm_flag,
                                    srtm_path=self.dlg.srtm_path(),
                                    plugin_dir=self.plugin_dir,
                                    azimuth_source=az_src,
                                    resnet_csv=resnet_csv_path if az_src == "resnet" else None
                                )
                                declination_outputs.append((f"{az_src}_{label}", out))
                            except Exception as _e:
                                self.iface.messageBar().pushWarning(
                                    "ArchaeoAstroInsight ",
                                    f"Declination {az_src}/{label} skipped: {_e}"
                                )

                    # --- Build the centralized Results CSV from whatever succeeded
                    #     (the old declinations.csv merge is dropped; results.csv supersedes it). ---
                    if declination_outputs:
                        _resnet_csv = resnet_csv_path if ('resnet_csv_path' in locals() and resnet_csv_path) else None
                        try:
                            self._build_results_csv(
                                declination_outputs,
                                out_dir,
                                resnet_csv_path=_resnet_csv,
                            )
                        except Exception as e:
                            self.iface.messageBar().pushWarning(
                                "ArchaeoAstroInsight ", f"Results CSV skipped: {e}"
                            )
                        self.iface.messageBar().pushInfo(
                            "ArchaeoAstroInsight ",
                            "Declination analysis completed."
                        )
                    else:
                        self.iface.messageBar().pushWarning(
                            "ArchaeoAstroInsight ",
                            "Declination analysis produced no results (all horizon methods failed)."
                        )
                

                

                # --- NEW: curvigram step (optional, runs AFTER feature detection) ---
                # Only run if checkbox is on
                compute_curvigrams = bool(getattr(self.dlg, "curvigramCheck", None) and self.dlg.curvigramCheck.isChecked())
                if compute_curvigrams:
                    # We may have up to two sources:
                    #   A) Feature-detection azimuth CSV in <out_dir>/features_results
                    #   B) ResNet predictions CSV (resnet_csv_path if ResNet block ran)
                    did_any = False

                    # (Helga feature-detection curvigrams removed in the ResNet-only light version)

                    # --- B) ResNet curvigram (single figure from azimuth_deg) ---
                    try:
                        # 'resnet_csv_path' exists only if ResNet block ran successfully
                        if 'resnet_csv_path' in locals() and resnet_csv_path and os.path.isfile(resnet_csv_path):
                            prog.setLabelText("Computing curvigrams (ResNet)…")

                            def _curvi_res_cb(pct: int):
                                pct = max(0, min(100, int(pct)))
                                _set_progress(99 + int(pct * 0.01))  # 99..100 (tiny tail)

                            res_resnet = run_curvigram_from_resnet_csv_single(
                                csv_path=resnet_csv_path,
                                latitude=45.0,     # TODO: expose in UI if needed
                                h_eff_deg=3.0,
                                iterations=20,
                                save_dir=os.path.join(out_dir, "Results"),
                                progress_cb=_curvi_res_cb,
                            )
                            self.iface.messageBar().pushInfo("ArchaeoAstroInsight ", f"Curvigrams (ResNet) saved: {res_resnet['figure_path']}")
                            did_any = True
                    except Exception as e:
                        self.iface.messageBar().pushWarning("ArchaeoAstroInsight ", f"Curvigram (ResNet) skipped: {e}")

                    # --- C) Declination curvigrams (HWT / SRTM, from results.csv) ---
                    try:
                        _results_csv = os.path.join(out_dir, "Results", "results.csv")
                        _do_hwt  = bool(self.dlg.use_declination_hwt())
                        _do_srtm = bool(self.dlg.use_declination_srtm())
                        if os.path.isfile(_results_csv) and (_do_hwt or _do_srtm):
                            prog.setLabelText("Computing declination curvigrams…")

                            def _curvi_decl_cb(pct: int):
                                pct = max(0, min(100, int(pct)))
                                _set_progress(99 + int(pct * 0.01))

                            res_decl = run_declination_curvigrams(
                                _results_csv,
                                save_dir=os.path.join(out_dir, "Results"),
                                h_eff_deg=3.0,
                                iterations=20,
                                do_hwt=_do_hwt,
                                do_srtm=_do_srtm,
                                progress_cb=_curvi_decl_cb,
                            )
                            if res_decl:
                                self.iface.messageBar().pushInfo("ArchaeoAstroInsight ", f"Declination curvigrams saved: {list(res_decl.keys())}")
                                did_any = True
                    except Exception as e:
                        self.iface.messageBar().pushWarning("ArchaeoAstroInsight ", f"Declination curvigrams skipped: {e}")

                    if not did_any:
                        self.iface.messageBar().pushWarning("ArchaeoAstroInsight ", "Curvigrams skipped: no suitable CSV found.")

                # --- Consolidate outputs into Results/ --------------------------------
                # Keep (renamed) the Monte-Carlo azimuth runs and the ResNet predictions;
                # drop the redundant per-method / merged declination CSVs and logs
                # (results.csv already holds the final values). Then remove the now-empty
                # features_results/ and test_results/ folders. Runs last, after every
                # step has finished reading those files.
                try:
                    import shutil, glob
                    results_dir = os.path.join(out_dir, "Results")
                    os.makedirs(results_dir, exist_ok=True)
                    fr_dir = os.path.join(out_dir, "features_results")
                    tr_dir = os.path.join(out_dir, "test_results")

                    def _keep_as(src_glob, dest_name):
                        matches = sorted(glob.glob(src_glob))
                        if matches:
                            dest = os.path.join(results_dir, dest_name)
                            if os.path.exists(dest):
                                os.remove(dest)
                            shutil.move(matches[-1], dest)

                    # Keep the ResNet predictions, with a clearer name
                    _keep_as(os.path.join(tr_dir, "classes_*.csv"), "resnet_predictions.csv")

                    # Drop the redundant declination CSVs + feature-detection logs
                    for _p in (glob.glob(os.path.join(fr_dir, "declinations*.csv"))
                               + glob.glob(os.path.join(fr_dir, "*.txt"))):
                        try:
                            os.remove(_p)
                        except Exception:
                            pass

                    # Remove the working folders only if nothing important remains
                    for _d in (fr_dir, tr_dir):
                        try:
                            if os.path.isdir(_d) and not os.listdir(_d):
                                os.rmdir(_d)
                        except Exception:
                            pass
                except Exception as _e:
                    self.iface.messageBar().pushWarning("ArchaeoAstroInsight ", f"Results consolidation skipped: {_e}")

                                        
                 



            else:
                # If no azimuth requested but we exported, at least reach 100
                _set_progress(100)


        except Exception as e:
            self.iface.messageBar().pushCritical("ArchaeoAstroInsight ", f"Error: {e}")
        finally:
            # Close the progress dialog AFTER detection+export, not earlier
            try:
                prog.setValue(100)
                prog.close()
                QApplication.processEvents()
            except Exception:
                pass
            QApplication.restoreOverrideCursor()

             









