# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ArcheDetectionDialog
                                 A QGIS plugin
 This plugin detects ground level objects from satellite imagery
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-08-22
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Andrei Ancuta
        email                : andrei.ancuta@e-uvt.ro
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 3 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic, QtWidgets
from qgis.PyQt.QtWidgets import QFileDialog
from qgis.PyQt.QtCore import QSettings
from qgis.core import QgsProject, QgsMapLayer, QgsVectorLayer, QgsWkbTypes


# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'arche_detection_dialog_base.ui'
))


class ArcheDetectionDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        super(ArcheDetectionDialog, self).__init__(parent)
        self.setupUi(self)

        settings = QSettings()

        # ----------------------------------------------------------
        # Optional runtime creation of widgets if missing from .ui
        # ----------------------------------------------------------

        # If polygon widgets already exist in the .ui, just wire them.
        # If they do NOT exist (no Designer edits), create them once.
        create_polygon_widgets = not (hasattr(self, "usePolyCheck") and
                                      hasattr(self, "polygonLayerCombo") and
                                      hasattr(self, "polygonLayerLabel"))

        if create_polygon_widgets:
            # Create at runtime (ONLY if not in the .ui)
            self.usePolyCheck = QtWidgets.QCheckBox("Use existing polygons (SHP)", self)
            self.polygonLayerLabel = QtWidgets.QLabel("Polygons layer:", self)
            self.polygonLayerCombo = QtWidgets.QComboBox(self)

            # Place them under the raster controls (absolute positioning)
            rgeom = self.rasterCombo.geometry()
            lgeom = getattr(self, "rasterLabel", None)
            insert_y = rgeom.y() + rgeom.height() + 8

            x_label = lgeom.x() if lgeom else rgeom.x()
            x_combo = rgeom.x()
            self.usePolyCheck.setGeometry(x_label, insert_y, max(220, rgeom.width() // 2), 22)
            self.polygonLayerLabel.setGeometry(x_label, insert_y + 26, 120, 22)
            self.polygonLayerCombo.setGeometry(x_combo, insert_y + 26, rgeom.width(), 24)

            # Push existing rows down so nothing overlaps
            delta = 56
            base_y = getattr(self, "modelLabel", self.modelPathEdit).y() if hasattr(self, "modelLabel") else (insert_y + 26)
            maybe_widgets = [
                "modelLabel", "modelPathEdit", "modelBrowseBtn",
                "confidenceLabel", "confidenceSpinBox",
                "exportCropsCheck", "exportDirEdit", "exportBrowseBtn",
                "azimuthCheck", "mcRunsLabel", "mcRunsSpin", "mcStdLabel", "mcStdSpin",
                "curvigramCheck", "resnetCheck", "resnetModelLabel", "resnetModelEdit", "resnetModelBrowseBtn",
                "button_box"
            ]
            for name in maybe_widgets:
                w = getattr(self, name, None)
                if w and hasattr(w, "y") and w.y() >= base_y:
                    w.move(w.x(), w.y() + delta)

        # ----------------------------------------------------------
        # Overlap spinbox (0..99%) wiring
        # ----------------------------------------------------------

        # If overlapSpinBox exists in the .ui (recommended), use it.
        # Otherwise create it at runtime.
        if not hasattr(self, "overlapSpinBox"):
            # Runtime create near confidence controls (absolute positioning)
            self.overlapLabel = QtWidgets.QLabel("Tile overlap (%)", self)
            self.overlapSpinBox = QtWidgets.QSpinBox(self)

            self.overlapSpinBox.setRange(0, 99)
            self.overlapSpinBox.setSuffix("%")
            self.overlapSpinBox.setValue(25)

            # Place it under confidence if possible
            if hasattr(self, "confidenceSpinBox") and hasattr(self, "confidenceLabel"):
                cbox = self.confidenceSpinBox.geometry()
                clab = self.confidenceLabel.geometry()
                y = cbox.y() + cbox.height() + 12

                self.overlapLabel.setGeometry(clab.x(), y, 140, 20)
                self.overlapSpinBox.setGeometry(cbox.x(), y, cbox.width(), 24)

            else:
                # Fallback placement
                self.overlapLabel.setGeometry(55, 340, 140, 20)
                self.overlapSpinBox.setGeometry(170, 340, 90, 24)

            # If we dynamically inserted this, we may need to push items below it down.
            # Only do it if we can safely detect overlap region.
            try:
                delta = 32
                base_y = self.overlapSpinBox.y()
                maybe_widgets = [
                    "exportCropsCheck", "exportDirEdit", "exportBrowseBtn",
                    "azimuthCheck", "mcRunsLabel", "mcRunsSpin", "mcStdLabel", "mcStdSpin",
                    "curvigramCheck", "resnetCheck", "resnetModelLabel", "resnetModelEdit", "resnetModelBrowseBtn",
                    "button_box"
                ]
                for name in maybe_widgets:
                    w = getattr(self, name, None)
                    if w and hasattr(w, "y") and w.y() >= base_y:
                        w.move(w.x(), w.y() + delta)
            except Exception:
                pass

        # Restore last-used overlap percent (default 25)
        last_overlap = settings.value("ArcheDetection/tile_overlap_percent", 25, type=int)
        try:
            last_overlap = max(0, min(int(last_overlap), 99))
        except Exception:
            last_overlap = 25
        self.overlapSpinBox.setValue(last_overlap)

        # Persist overlap when changed
        def _save_overlap(v):
            try:
                v = max(0, min(int(v), 99))
            except Exception:
                v = 25
            QSettings().setValue("ArcheDetection/tile_overlap_percent", v)

        self.overlapSpinBox.valueChanged.connect(_save_overlap)

        # ----------------------------------------------------------
        # Populate polygons combo
        # ----------------------------------------------------------
        def _populate_polygon_layers():
            self.polygonLayerCombo.clear()
            for lyr in QgsProject.instance().mapLayers().values():
                if isinstance(lyr, QgsVectorLayer) and QgsWkbTypes.geometryType(lyr.wkbType()) == QgsWkbTypes.PolygonGeometry:
                    self.polygonLayerCombo.addItem(lyr.name(), lyr.id())

        _populate_polygon_layers()
        QgsProject.instance().layersAdded.connect(lambda *_: _populate_polygon_layers())
        QgsProject.instance().layersRemoved.connect(lambda *_: _populate_polygon_layers())

        # Hide/show YOLO controls when polygon mode is toggled
        self._yolo_widgets = [
            w for w in [
                getattr(self, "modelLabel", None),
                getattr(self, "modelPathEdit", None),
                getattr(self, "modelBrowseBtn", None),
                getattr(self, "confidenceLabel", None),
                getattr(self, "confidenceSpinBox", None),
                getattr(self, "overlapLabel", None),
                getattr(self, "overlapSpinBox", None),
            ] if w is not None
        ]

        def _toggle_polygon_mode(on: bool):
            self.polygonLayerCombo.setEnabled(on)
            self.polygonLayerLabel.setEnabled(on)
            for w in self._yolo_widgets:
                w.setVisible(not on)

        self.usePolyCheck.toggled.connect(_toggle_polygon_mode)
        _toggle_polygon_mode(self.usePolyCheck.isChecked())

        # Helpers for main plugin
        self.is_polygon_mode = lambda: self.usePolyCheck.isChecked()
        self.selected_polygon_layer_id = lambda: self.polygonLayerCombo.currentData()
        self.tile_overlap_percent = lambda: int(self.overlapSpinBox.value())

        # ----------------------------------------------------------
        # Export / Azimuth / ResNet UI
        # ----------------------------------------------------------

        # 1) Populate on open
        self.populate_raster_combo()
        QgsProject.instance().layersAdded.connect(self.populate_raster_combo)
        QgsProject.instance().layersRemoved.connect(self.populate_raster_combo)

        # 2) Remember last-used YOLO model
        last_model = settings.value("ArcheDetection/model_path", "", type=str)
        if last_model and hasattr(self, "modelPathEdit"):
            self.modelPathEdit.setText(last_model)

        def _pick_model():
            start = self.modelPathEdit.text().strip() if hasattr(self, "modelPathEdit") else (last_model or "")
            path, _ = QFileDialog.getOpenFileName(
                self, "Choose YOLO model", start, "PyTorch weights (*.pt *.pth);;All files (*)"
            )
            if path and hasattr(self, "modelPathEdit"):
                self.modelPathEdit.setText(path)
                QSettings().setValue("ArcheDetection/model_path", path)

        if hasattr(self, "modelBrowseBtn"):
            self.modelBrowseBtn.clicked.connect(_pick_model)

        # 3) ResNet: remember last-used .keras and browse handler
        last_resnet = settings.value("ArcheDetection/resnet_model", "", type=str)
        if last_resnet and hasattr(self, "resnetModelEdit"):
            self.resnetModelEdit.setText(last_resnet)

        def _pick_resnet():
            start = self.resnetModelEdit.text().strip() if hasattr(self, "resnetModelEdit") else (last_resnet or "")
            path, _ = QFileDialog.getOpenFileName(
                self, "Choose ResNet .keras model", start, "Keras model (*.keras);;All files (*)"
            )
            if path and hasattr(self, "resnetModelEdit"):
                self.resnetModelEdit.setText(path)
                QSettings().setValue("ArcheDetection/resnet_model", path)

        if hasattr(self, "resnetModelBrowseBtn"):
            self.resnetModelBrowseBtn.clicked.connect(_pick_resnet)

        # 4) Master toggle for "Also export crops": gates azimuth + resnet
        def _toggle_export(on: bool):
            # export folder widgets
            for wname in ("exportDirEdit", "exportBrowseBtn"):
                w = getattr(self, wname, None)
                if w:
                    w.setEnabled(bool(on))

            # gate azimuth + resnet checkboxes when export is ON
            if hasattr(self, "azimuthCheck"):
                self.azimuthCheck.setEnabled(bool(on))
            if hasattr(self, "resnetCheck"):
                self.resnetCheck.setEnabled(bool(on))

            # update sub-controls
            try:
                _update_mc_controls()  # defined below
            except Exception:
                pass

            # resnet path widgets depend on BOTH export and resnet checkbox
            _toggle_resnet(self.resnetCheck.isChecked() if hasattr(self, "resnetCheck") else False)

        # 5) Azimuth sub-controls
        def _toggle_azimuth(on: bool):
            az_enabled = on and self.exportCropsCheck.isChecked()

            for wname in ("mcRunsLabel", "mcRunsSpin"):
                w = getattr(self, wname, None)
                if w:
                    w.setEnabled(az_enabled)

            # NEW: YOLO azimuth checkbox depends on azimuth pipeline
            if hasattr(self, "useYoloMonteCheck"):
                self.useYoloMonteCheck.setEnabled(az_enabled)

        if hasattr(self, "azimuthCheck"):
            self.azimuthCheck.toggled.connect(_toggle_azimuth)

        if hasattr(self, "declinationCheck"):
            self.declinationCheck.setEnabled(False)

        def use_srtm(self):
            return hasattr(self, "srtmCheck") and self.srtmCheck.isChecked()

        def _toggle_srtm(on: bool):
            for wname in ("srtmPathEdit", "srtmBrowseBtn"):
                w = getattr(self, wname, None)
                if w:
                    w.setEnabled(on)

        def _toggle_declination_srtm(on: bool):
            for wname in ("srtmPathEdit", "srtmBrowseBtn"):
                w = getattr(self, wname, None)
                if w:
                    w.setEnabled(on)

        if hasattr(self, "declinationSRTMCheck"):
            self.declinationSRTMCheck.toggled.connect(_toggle_declination_srtm)
            _toggle_declination_srtm(self.declinationSRTMCheck.isChecked())

        def _pick_srtm():
            path = QFileDialog.getExistingDirectory(
                self,
                "Choose folder containing SRTM tiles"
            )
            if path and hasattr(self, "srtmPathEdit"):
                self.srtmPathEdit.setText(path)

        if hasattr(self, "srtmBrowseBtn"):
            self.srtmBrowseBtn.clicked.connect(_pick_srtm)

        def srtm_path(self):
            if hasattr(self, "srtmPathEdit"):
                return self.srtmPathEdit.text().strip()
            return ""

        def _update_mc_controls():
            export_on = bool(getattr(self, "exportCropsCheck", None) and self.exportCropsCheck.isChecked())
            az_on     = bool(getattr(self, "azimuthCheck", None) and self.azimuthCheck.isChecked())
            runs_spin = getattr(self, "mcRunsSpin", None)
            runs_val  = runs_spin.value() if runs_spin else 1

            # Runs widgets show when azimuth+export are on
            for w in ("mcRunsLabel", "mcRunsSpin"):
                ww = getattr(self, w, None)
                if ww:
                    ww.setEnabled(bool(export_on and az_on))

            # StdDev widgets only when runs > 1
            show_std = export_on and az_on and (runs_val > 1)
            for w in ("mcStdLabel", "mcStdSpin"):
                ww = getattr(self, w, None)
                if ww:
                    ww.setEnabled(bool(show_std))

            # (curvigram enabling moved to _toggle_resnet in the ResNet-only light version)

        # 6) ResNet path widgets depend on BOTH export and resnet checkbox
        def _toggle_resnet(on: bool):
            export_on = bool(getattr(self, "exportCropsCheck", None) and self.exportCropsCheck.isChecked())
            enable = bool(on and export_on)

            for wname in ("resnetModelEdit", "resnetModelBrowseBtn"):
                w = getattr(self, wname, None)
                if w:
                    w.setEnabled(enable)

            # NEW: ResNet azimuth checkbox depends on resnetCheck
            if hasattr(self, "useResnetCheck"):
                self.useResnetCheck.setEnabled(enable)

            # Curvigrams become available once the ResNet pipeline will run
            if hasattr(self, "curvigramCheck"):
                self.curvigramCheck.setEnabled(enable)

        if hasattr(self, "resnetCheck"):
            self.resnetCheck.toggled.connect(_toggle_resnet)

        # 7) Wire master export switch
        if hasattr(self, "exportCropsCheck"):
            self.exportCropsCheck.toggled.connect(_toggle_export)
            _toggle_export(self.exportCropsCheck.isChecked())

        # 8) Keep mc controls reactive
        if hasattr(self, "azimuthCheck"):
            self.azimuthCheck.toggled.connect(lambda _: _update_mc_controls())
        if hasattr(self, "mcRunsSpin"):
            self.mcRunsSpin.valueChanged.connect(lambda _: _update_mc_controls())
        _update_mc_controls()

        # 9) Export dir picker
        def _pick_dir():
            path = QFileDialog.getExistingDirectory(self, "Choose output folder for PNG crops")
            if path and hasattr(self, "exportDirEdit"):
                self.exportDirEdit.setText(path)

        if hasattr(self, "exportBrowseBtn"):
            self.exportBrowseBtn.clicked.connect(_pick_dir)

        # Ensure correct initial states

        if hasattr(self, "useYoloMonteCheck"):
            self.useYoloMonteCheck.setEnabled(
                hasattr(self, "azimuthCheck") and self.azimuthCheck.isChecked()
            )

        if hasattr(self, "useResnetCheck"):
            # Implicit ResNet azimuths: keep the widget (so its signal wiring and any
            # future azimuth-source logic stay intact) but force it on and hide it.
            self.useResnetCheck.setChecked(True)
            self.useResnetCheck.setVisible(False)

        def _update_declination_controls():
            use_feature = hasattr(self, "useYoloMonteCheck") and self.useYoloMonteCheck.isChecked()
            # ResNet azimuths are implicit now; the declination methods are available whenever
            # the ResNet pipeline will actually run (Classify + Export both on).
            export_on   = bool(getattr(self, "exportCropsCheck", None) and self.exportCropsCheck.isChecked())
            resnet_on   = bool(getattr(self, "resnetCheck", None) and self.resnetCheck.isChecked())
            use_resnet  = resnet_on and export_on

            enable = use_feature or use_resnet

            if hasattr(self, "declinationHWTCheck"):
                self.declinationHWTCheck.setEnabled(enable)

            if hasattr(self, "declinationSRTMCheck"):
                self.declinationSRTMCheck.setEnabled(enable)

        if hasattr(self, "useYoloMonteCheck"):
            self.useYoloMonteCheck.toggled.connect(lambda _: _update_declination_controls())

        if hasattr(self, "useResnetCheck"):
            self.useResnetCheck.toggled.connect(lambda _: _update_declination_controls())

        # useResnetCheck is hidden/implicit now, so drive the declination controls off
        # the real ResNet pipeline switches instead.
        if hasattr(self, "resnetCheck"):
            self.resnetCheck.toggled.connect(lambda _: _update_declination_controls())
        if hasattr(self, "exportCropsCheck"):
            self.exportCropsCheck.toggled.connect(lambda _: _update_declination_controls())

        _update_declination_controls()

    def populate_raster_combo(self):
        """Fill the combo with all raster layers in the project."""
        self.rasterCombo.clear()
        for lyr in QgsProject.instance().mapLayers().values():
            if lyr.type() == QgsMapLayer.RasterLayer:
                # Store the layer ID in userData so we can retrieve the exact layer later
                self.rasterCombo.addItem(lyr.name(), lyr.id())

    def use_declination_hwt(self):
        return hasattr(self, "declinationHWTCheck") and self.declinationHWTCheck.isChecked()

    def use_declination_srtm(self):
        return hasattr(self, "declinationSRTMCheck") and self.declinationSRTMCheck.isChecked()

    def use_feature_azimuth(self):
        return hasattr(self, "useYoloMonteCheck") and self.useYoloMonteCheck.isChecked()

    def use_resnet_azimuth(self):
        # ResNet azimuths are now implicit / always-on. The old "Use Resnet azimuths"
        # checkbox is kept in the dialog but hidden and forced checked, so the backend
        # logic ("if use_resnet: azimuth_sources.append('resnet')") is unchanged and a
        # second azimuth source can be added the same way later.
        return True

    def srtm_path(self):
        """Return selected SRTM path."""
        if hasattr(self, "srtmPathEdit"):
            return self.srtmPathEdit.text().strip()
        return ""
